// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// InMemoryClient is an autogenerated mock type for the InMemoryClient type
type InMemoryClient struct {
	mock.Mock
}

// GetValue provides a mock function with given fields: ctx, key
func (_m *InMemoryClient) GetValue(ctx context.Context, key string) string {
	ret := _m.Called(ctx, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetKeyValue provides a mock function with given fields: ctx, key, value
func (_m *InMemoryClient) SetKeyValue(ctx context.Context, key string, value string) error {
	ret := _m.Called(ctx, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
