// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import contract "github.com/discoverAnkit/getir/contract"
import mock "github.com/stretchr/testify/mock"

import time "time"

// MongoClient is an autogenerated mock type for the MongoClient type
type MongoClient struct {
	mock.Mock
}

// GetRecordsByCreationTime provides a mock function with given fields: ctx, startTime, endTime
func (_m *MongoClient) GetRecordsByCreationTime(ctx context.Context, startTime time.Time, endTime time.Time) ([]contract.KVRecord, error) {
	ret := _m.Called(ctx, startTime, endTime)

	var r0 []contract.KVRecord
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []contract.KVRecord); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contract.KVRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
